### ISSUE TITLE
Load-Balancer does not work

### ISSUE THREAD

**Issue by Andy1822** [jakeprobst/anki-loadbalancer#13]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.16 (4bc33e2f) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=1
Add-ons possibly involved: load balancer

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 322, in handler
  File "aqt/reviewer.py", line 281, in _onAnswerButton
  File "aqt/reviewer.py", line 237, in _answerCard
  File "anki/sched.py", line 83, in answerCard
  File "anki/sched.py", line 527, in _answerLrnCard
  File "/Users/ASF75197/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 163, in NEW_rescheduleAsRev
    card.ivl = NEW_adjRevIvl(self, card, card.ivl)
  File "/Users/ASF75197/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 112, in NEW_adjRevIvl
    p(BeautifulSoup(card.render_output().question_text, "html.parser").getText())
AttributeError: 'Card' object has no attribute 'render_output'

**Comment by Andy1822** [comment]
Each time I hit the space bar to move on to the next card, I get this error message

**Comment by AltusMightus** [comment]
I am having the same issue, started after I updated the add-on from the latest version:

Debug info:
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 317, in handler
  File "aqt\reviewer.py", line 281, in _onAnswerButton
  File "aqt\reviewer.py", line 237, in _answerCard
  File "<decorator-gen-58>", line 2, in answerCard
  File "anki\hooks.py", line 74, in decorator_wrapper
  File "anki\hooks.py", line 65, in repl
  File "anki\sched.py", line 83, in answerCard
  File "anki\sched.py", line 527, in _answerLrnCard
  File "C:\Users\Nikolas\AppData\Roaming\Anki2\addons21\1417170896\loadbalancer.py", line 161, in NEW_rescheduleAsRev
    OLD_rescheduleAsRev(self, card, conf, early)
  File "anki\sched.py", line 598, in _rescheduleAsRev
  File "anki\sched.py", line 654, in _rescheduleNew
  File "anki\sched.py", line 648, in _graduatingIvl
  File "C:\Users\Nikolas\AppData\Roaming\Anki2\addons21\1417170896\loadbalancer.py", line 112, in NEW_adjRevIvl
    p(BeautifulSoup(card.render_output().question_text, "html.parser").getText())
<class 'AttributeError'>: 'Card' object has no attribute 'render_output'

**Comment by jakeprobst** [comment]
version mismatching, anki 2.1.20 changed a function I was using and so in the process of making it work on new anki it broke on old anki, update to the latest anki to have it keep working.

**Comment by Cardosaum** [comment]
Additionally, @Andy1822 and @AltusMightus,

`loadbalancer` can be changed to a previous version if upgrading `Anki` to `2.1.20` is not an option for now.

See #12 for more details.
