### ISSUE TITLE
Breakage: type object 'Collection' has no attribute 'load'

### ISSUE THREAD

**Issue by twwn** [jakeprobst/anki-loadbalancer#15]
Bugs out on start of most recent anki-git with

```
When loading '⁨load balancer⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aqt/addons.py", line 211, in loadAddons
    __import__(addon.dir_name)
  File "/home/meme/.local/share/Anki2/addons21/1417170896/__init__.py", line 1, in <module>
    from . import loadbalancer
  File "/home/meme/.local/share/Anki2/addons21/1417170896/loadbalancer.py", line 512, in <module>
    anki.collection._Collection.load = wrap(anki.collection._Collection.load, InitConf, pos="after")
AttributeError: type object 'Collection' has no attribute 'load'
```

**Comment by andrewcrook** [comment]
I got the same since Anki automatically updated

Anki Version 2.1.28 (7d8818f8)
Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
macOS 10.15.6

```
When loading '⁨load balancer⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/andrew/Library/Application Support/Anki2/addons21/1417170896/__init__.py", line 1, in <module>
    from . import loadbalancer
  File "/Users/andrew/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 512, in <module>
    anki.collection._Collection.load = wrap(anki.collection._Collection.load, InitConf, pos="after")
AttributeError: type object 'Collection' has no attribute 'load'
```

**Comment by jakeprobst** [comment]
fixed
