### ISSUE TITLE
Issue with loadbalancer on anki 2.1.29 with V7

### ISSUE THREAD

**Issue by pvansch** [jakeprobst/anki-loadbalancer#19]
Hi there, I hope you are doing well. I updated anki to 2.1.29 and just added version V7. When I do my first card and go to move onto the next card this is the error message I get. Once I go to add ons and delete load balancer and restart, then my deck works like normal, just the loadbalancer addon is not there. Any advice?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-04 15:09:45
Add-ons possibly involved: ⁨load balancer⁩

Caught exception:
Traceback (most recent call last):
  File "anki/config.py", line 35, in get_immutable
  File "anki/rsbackend_gen.py", line 570, in get_config_json
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.NotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/webview.py", line 490, in handler
  File "aqt/reviewer.py", line 320, in _onAnswerButton
  File "aqt/reviewer.py", line 257, in _answerCard
  File "anki/sched.py", line 76, in answerCard
  File "anki/sched.py", line 531, in _answerRevCard
  File "anki/sched.py", line 577, in _rescheduleRev
  File "anki/sched.py", line 618, in _updateRevIvl
  File "/Users/paulvanschuyver/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 46, in NEW_adjRevIvl
    ivlmin = idealIvl - min(qc["LBMaxBefore"], int(idealIvl*qc["LBPercentBefore"]))
  File "anki/config.py", line 49, in __getitem__
  File "anki/config.py", line 37, in get_immutable
KeyError

**Comment by jakeprobst** [comment]
looks like its not loading the configuration correctly

**Comment by pvansch** [comment]
Thank you for the fast response. What is the best way for me to fix the issue? Thank you.

**Comment by jakeprobst** [comment]
I can reproduce it, the addon isn't setting the default config values properly.

I'll try and get a fix out soon.

**Comment by pvansch** [comment]
Okay sounds great. Thank you for your help.

**Comment by jakeprobst** [comment]
this should be resolved
