### ISSUE TITLE
Load Balancer seems to fail at version 23.12.1 (no module named 'anki.sched')

### ISSUE THREAD

**Issue by MartinVogtFHNW** [jakeprobst/anki-loadbalancer#28]
Unfortunately, the load balancer can no longer be used with the latest version of Anki.

![Screenshot 2024-02-08 at 17 25 04](https://github.com/jakeprobst/anki-loadbalancer/assets/113760890/56392e05-70ba-4eb0-aa6d-ae36adc9a607)

**Debug Info**:
```
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

When loading load balancer:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/USERNAME/Library/Application Support/Anki2/addons21/1417170896/__init__.py", line 1, in <module>
    from . import loadbalancer
  File "/Users/USERNAME/Library/Application Support/Anki2/addons21/1417170896/loadbalancer.py", line 6, in <module>
    from anki.sched import Scheduler
ModuleNotFoundError: No module named 'anki.sched'
```

**Comment by MartinVogtFHNW** [comment]
[Add-ons and custom scheduling](https://faqs.ankiweb.net/the-2021-scheduler.html#add-ons-and-custom-scheduling)
The new scheduler is a ground-up rewrite, so add-ons that modified the old scheduler's card gathering or answering routines will no longer work. It is no longer possible to selectively replace parts of the scheduler's code ("monkey patching"), **so some add-ons may not be practical to port without significant effort.**

The new scheduler does provide some control over the scheduling however. As each card is presented, the times and states associated with each answer button are calculated in advance, and it is possible to modify the calculated scheduling with some JavaScript code entered into the bottom of the deck options screen.

The code you enter applies to the entire collection, and not just decks using the preset.
