### ISSUE TITLE
The following add-ons failed to load: ⁨ load balancer⁩ They may need to be updated to support this version of Anki

### ISSUE THREAD

**Issue by imadoddinquadari** [jakeprobst/anki-loadbalancer#29]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22631

When loading load balancer:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\91703\AppData\Roaming\Anki2\addons21\1417170896\__init__.py", line 1, in <module>
    from . import loadbalancer
  File "C:\Users\91703\AppData\Roaming\Anki2\addons21\1417170896\loadbalancer.py", line 6, in <module>
    from anki.sched import Scheduler
ModuleNotFoundError: No module named 'anki.sched'

**Comment by dhruvbhangale** [comment]
please update it
